### DISCUSSION TITLE
Delivery acknowledgement on channel 1 timed out

### DISCUSSION THREAD

**Discussion by nopromise** [spring-projects/spring-amqp#2554] [General]
I got a very weird question.I use Spring Cloud Stream and I have a consumer to listen a queue(truck-event-topic.device),when I started my Spring Boot service,the consumer did listen this queue and prefetched one message as follows.But the message didn't go inside my consumer code.It should go inside my consumer code and print a log and execute my business code.Finally,when the time reached 30 minutes,I got the "delivery acknowledgement on channel 1 timed out" exception.
I don't know why this happened .Any chance it has something to do with mirrored queues?

**The exception message**
![image](https://github.com/spring-projects/spring-amqp/assets/16243165/fab40285-6454-4827-8d34-011e69b3f1f9)

**The configuration is as follows:**
```yaml
spring:
  cloud:
    stream:
      default:
        consumer:
          concurrency: 1
          maxAttempts: 10000
          backOffInitialInterval: 500
          backOffMaxInterval: 60000
          backOffMultiplier: 2.0
      function:
        definition: truckEvent
      bindings:
        truckEvent-in-0:
          destination: truck-event-topic
          content-type: application/json
          group: device

  rabbitmq:
    username: ******
    password: ******
    virtual-host: /test
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        prefetch: 20
    cache:
      channel:
        size: 1000
      connection:
        mode: channel
    requested-channel-max: 2047
    addresses: ******,******,******

```

**The truck-event-topic.device**
![image](https://github.com/spring-projects/spring-amqp/assets/16243165/00112cca-be30-435c-bb56-7b2cda773286)

**This queue prefetch a message**
![image](https://github.com/spring-projects/spring-amqp/assets/16243165/abb562b1-f326-4975-8f97-9af7df417476)

**My consumer code**
![image](https://github.com/spring-projects/spring-amqp/assets/16243165/9684bf70-bf86-4216-be71-5364981a8047)
