### ISSUE TITLE
Unacked messages in queue

### ISSUE THREAD

**Issue by jdathor** [spring-projects/spring-amqp#1241]
**Affects Version(s):** \<2.0.5.RELEASE>

---

Hi, 

My team is encountering issue in our rabbitmq consumer that happens rarely. We are running multiple instance of our spring-boot application in PCF with autoscaler and tried to replicate this several times by scaling it up/down but it was unsuccessful.

It seems that there is a similar issue before with different scenario: 
Unacked messages when using SimpleMessageListenerContainer (https://github.com/spring-projects/spring-amqp/issues/694)

Here is the sample consumer listener that we have, maybe we are missing configurations or something.
```
 @StreamListener(Constants.QUEUE_RECEIVER)
 public void queueReceiver(Payload payload) {
        log.info("[MQReceiverService] Received event | payload = {}", JacksonUtil.getInstance().writeValueAsString(payload));
        < . . . >
 }
```
Note that the queueReceiver didn't actually received the message as there are no logged logs. Maybe the message was stuck somewhere in the process.

Configuration:
```
spring:
  cache:
    type: none
  cloud:
    stream:
      bindings:
        queueReceiver: #Receive
          contentType: application/json
          destination: upload-doc
          group: upload-group.queueReceiver
          binder: rmq
      binders:
        rmq:
          type: rabbit
      rabbit:
        bindings:
          queueReceiver: #Receive
            consumer:
              requeue-rejected: true
              bindingRoutingKey: document.upload.complete
  rabbitmq:
    requested-heartbeat: 30
```

I also created a question in stackoverflow, (https://stackoverflow.com/questions/63465726/pcf-rabbitmq-unacked-messages-in-queue)

Thank you!
