### ISSUE TITLE
Add Alternate Exchange support

### ISSUE THREAD

**Issue by serut** [spring-projects/spring-amqp#1468]
**Expected Behavior**

There is tons of applications related to alternate-exchange that looks not address by the spring amqp right now. https://www.rabbitmq.com/ae.html

I would like to declare in my config file : 
```yml
spring:
  cloud:
      rabbit:
        bindings:
          <something>:
            producer:
              alternate-exchange-exchange: where.my.message.goes.when.routing.key.no.match
              alternate-exchange-type: topic
              alternate-exchange-queue-name: where.my.message.end.when.routing.key.no.match
```

**Current Behavior**

There is no way to declare an alternate exchange without using the low level AMQP API. It would be killer feature to be able to do it from inside application config file

**Context**

It would be used in case the producer send its first messages before the receiver creates its queue. The producer must declare an alternate-exchange on the exchange and a queue associated to the exchange to store messages that has not been routed to an existing queue using routing key.
